
logging:
  level:
    root: INFO
    '[org.springframework.security: trace]': TRACE

server.port: 9998
server:
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /management
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: 10000ms
    info:
      cache:
        time-to-live: 10000ms

spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ

  application:
    name: auth-server-default

  threads:
    virtual:
      enabled: false

  security:
    user:
      name: user1
      password: user1
    oauth2:
      authorizationserver:
        client:
          messaging-client:
            registration:
              client-id: "attribute-client"
              client-secret: "{noop}attribute_secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/messaging-client-oidc"
                - "http://127.0.0.1:8080/authorized"
                - "http://localhost:9080/openapi/webjars/swagger-ui/oauth2-redirect.html"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "attribute:read"
                - "attribute:write"
            require-authorization-consent: true

app:
  eureka-server: ${EUREKA_SERVER}

security:
  eureka-username: ${EUREKA_USERNAME}
  eureka-password: ${EUREKA_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://${security.eureka-username}:${security.eureka-password}@${app.eureka-server}:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

