version: "3"

#
# https://github.com/peter-evans/docker-compose-healthcheck
#
services:

  opensearch-attr-db:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-attr-node
    ports:
      - 9200:9200
      - 9600:9600
    environment:
      - discovery.type=single-node