#!/bin/bash

set -e 

cd $(dirname $0)

#cat src/main/resources/banner.txt
#echo

Help()
{
   # Display Help
   echo "For the using of this script you need several parameters."
   echo
   echo "Syntax: [-e|-t|-m|-f|-P|-U|-W|-h]"
   echo "options:"
   echo "e     The endpoint name [management|v1/attributes]."
   echo "t     The token (required)."
   echo "m     The request method [GET(default)|POST]"
   echo "f     The name of the file that contains the restaurant to be added [newVideo01.json]."
   echo "P     The Http port [8080(default)|7001(otherwise)]."
   echo "U     The username."
   echo "W     The user password."
   echo "h     Print this Help."
   echo
}

while getopts ":e:i:t:m:f:P:U:W:h" arg; do
  case $arg in
    h) 	Help
    	exit;;
    e)	ENDPOINT=$OPTARG;;
    i)	ID=$OPTARG;;
    t)	TOKEN=$OPTARG;;
    P)  PORT=$OPTARG;;
    m)  METHOD=$OPTARG;;
    U)  USERNAME=$OPTARG;;
    W)  PASSWORD=$OPTARG;;
    f)  FILE=$OPTARG;;
    \?)	#incorrect option
    	echo "Error : invalid option"
    	echo
    	Help
    	exit;;
  esac
done

if [ -z $ENDPOINT ]
then ENDPOINT="v1/attributes"
fi

if [ -z $PORT ]
then PORT="8080"
fi

if [[ -z $USERNAME || -z $PASSWORD ]]
then
  USERNAME="user"
  PASSWORD="user"
fi

if [[ -z $METHOD ]]
then METHOD="GET"
fi

if [[ -n $METHOD && $METHOD == "POST" ]]
then http -a $USERNAME:$PASSWORD POST ":$PORT/$ENDPOINT" < attribute-dictionary-api/src/test/resources/json/$FILE
elif [[ -n $METHOD && $METHOD == "PUT" ]]
then http -a $USERNAME:$PASSWORD PUT ":$PORT/$ENDPOINT" < attribute-dictionary-api/src/test/resources/json/$FILE
elif [[ -n $METHOD && $METHOD == "DELETE" && -z $ID ]]
then http -a $USERNAME:$PASSWORD DELETE ":$PORT/$ENDPOINT"
elif [[ -n $METHOD && $METHOD == "DELETE" && -n $ID ]]
then http -a $USERNAME:$PASSWORD DELETE ":$PORT/$ENDPOINT/$ID"
elif [[ -n $ID ]]
then http -a $USERNAME:$PASSWORD ":$PORT/$ENDPOINT/$ID"
else 
	http -a $USERNAME:$PASSWORD ":$PORT/$ENDPOINT"
fi

exit 0
