#!/bin/bash

set -e 

cd $(dirname $0)

cat src/main/resources/banner.txt
echo

Help()
{
   # Display Help
   echo "For the using of this script you need several parameters."
   echo
   echo "Syntax: [-e|-m|-P|-U|-W|-h]"
   echo "options:"
   echo "e     The endpoint name [_cat/nodes?v|_cat/plugins?v]."
   echo "m     The request method [GET(default)|POST|PUT|DELETE]"
   echo "P     The Http port [8080(default)|7001(otherwise)]."
   echo "U     The username."
   echo "W     The user password."
   echo "h     Print this Help."
   echo "Visit https://hub.docker.com/r/opensearchproject/opensearch"
   echo
}

while getopts ":e:m:f:P:U:W:h" arg; do
  case $arg in
    h) 	Help
    	exit;;
    e)	ENDPOINT=$OPTARG;;
    P)  PORT=$OPTARG;;
    m)  METHOD=$OPTARG;;
    U)  USERNAME=$OPTARG;;
    W)  PASSWORD=$OPTARG;;
    f)  FILE=$OPTARG;;
    \?)	#incorrect option
    	echo "Error : invalid option"
    	echo
    	Help
    	exit;;
  esac
done

if [ -z $ENDPOINT ]
then ENDPOINT=""
fi

if [ -z $PORT ]
then PORT="9200"
fi

if [[ -z $USERNAME || -z $PASSWORD ]]
then
  USERNAME="admin"
  PASSWORD="admin"
fi

if [[ -z $METHOD ]]
then METHOD="GET"
fi

if [[ -n $METHOD && $METHOD == "POST" ]]
then http -a $USERNAME:$PASSWORD POST "https://localhost:$PORT/$ENDPOINT" < src/test/resources/json/$FILE --verify=no
elif [[ -n $METHOD && $METHOD == "PUT" ]]
then http -a $USERNAME:$PASSWORD PUT "https://localhost:$PORT/$ENDPOINT" < src/test/resources/json/$FILE --verify=no
elif [[ -n $METHOD && $METHOD == "DELETE" && -z $ID ]]
then http -a $USERNAME:$PASSWORD DELETE "https://localhost:$PORT/$ENDPOINT" --verify=no
elif [[ -n $METHOD && $METHOD == "DELETE" && -n $ID ]]
then http -a $USERNAME:$PASSWORD DELETE "https://localhost:$PORT/$ENDPOINT/$ID" --verify=no
elif [[ -n $ID ]]
then http -a $USERNAME:$PASSWORD "https://localhost:$PORT/$ENDPOINT/$ID" --verify=no
else 
	http -a $USERNAME:$PASSWORD "https://localhost:$PORT/$ENDPOINT" --verify=no
fi

exit 0
