#!/bin/bash

set -e

cd $(dirname $0)

docker run --rm -d --name video-api -p 8081:8081 -e JAVA_OPTS="-Xms512M -Xmx512M" \
-e SPRING_PROFILES_ACTIVE="dev" \
-e PSQL_USERNAME="michael" \
-e PSQL_PASSWORD="jordan" \
-e USER_PASSWORD="user" \
-e WRITER_PASSWORD="writer" \
-e ADMIN_PASSWORD="admin" video-api:latest

cd -