
logging:
  level:
    root: INFO

spring:
  # More information is here :
  # https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization.using-basic-sql-scripts
  # https://www.baeldung.com/spring-boot-data-sql-and-schema-sql
  sql:
    init:
      mode: never
      data-locations: optional:classpath*:sql/data.sql
      schema-locations: optional:classpath*:sql/schema.sql
      continue-on-error: false

  datasource:
    url: jdbc:postgresql://videos-db:5432/videoDatabase?loggerLevel=OFF
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath*:/liquibase/db.changelog-master.yaml
    url: jdbc:postgresql://videos-db:5432/videoDatabase
    user: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}