
logging:
  level:
    root: INFO

server.port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /management
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: 10000ms
    info:
      cache:
        time-to-live: 10000ms

springdoc:
  api-docs:
    path: /openapi/v3/api-docs
  swagger-ui:
    path: /openapi/swagger-ui.html
  paths-to-match: /**
  packages-to-scan: com.springboot.learning.sb3.controller

spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ

  application:
    name: pro-attribute-dictionary-api

  threads:
    virtual:
      enabled: false

  cloud:
    function:
      definition: attributeDictionarySyncEventConsume
    stream:
      default-binder: kafka

      bindings:
        attributeDictionarySyncEventConsume-in-0:
          destination: adeo-dev-europe-west1-APP-ARBOLPIM-BM-ES-P1-C1-BONSAI-DICTIONNARY-ATTRIBUTE-SYNC-V1
          group: svc-arbolpim-app-dev-BM-ES-SCS
          content-type: application/*+avro

          consumer:
            batch-mode: false
            partitioned: false
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-max-interval: 1000
            back-off-multiplier: 2.0

        attributeDictionarySyncEventConsume-out-0:
          destination: adeo-dev-europe-west1-APP-ARBOLPIM-BM-ES-P1-C1-BONSAI-DICTIONNARY-ATTRIBUTE-SYNC-V1
          content-type: application/*+avro

          producer:
            use-native-encoding: true
            required-groups:
              - auditGroup

api:
  pagination:
    page: 0
    size: 20

security:
  access:
    users:
      -
        username: user
        password: ${USER_PASSWORD}
        authorities:
          - READER
          - WRITER

      -
        username: user_writer
        password: ${WRITER_PASSWORD}
        authorities:
          - READER
          - WRITER

      -
        username: admin
        password: ${ADMIN_PASSWORD}
        authorities:
          - READER
          - WRITER
          - ADMIN

service.version: v1