
logging:
  level:
    root: INFO

spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/videoDatabase?loggerLevel=OFF
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}
    properties:
      validationQuery: select 1

  liquibase:
    enabled: true
    change-log: classpath*:/liquibase/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/videoDatabase
    user: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}