
logging:
  level:
    root: INFO

server.port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /management
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: 10000ms
    info:
      cache:
        time-to-live: 10000ms

spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ

  application:
    name: web-lab

  threads:
    virtual:
      enabled: false

  cloud:
    function:
      definition: attributeDictionarySyncEventConsume
    stream:
      default-binder: kafka

      bindings:
        attributeDictionarySyncEventConsume-in-0:
          destination: adeo-dev-europe-west1-APP-ARBOLPIM-BM-ES-P1-C1-BONSAI-DICTIONNARY-ATTRIBUTE-SYNC-V1
          group: svc-arbolpim-app-dev-BM-ES-SCS
          content-type: application/*+avro

          consumer:
            batch-mode: false
            partitioned: false

        attributeDictionarySyncEventConsume-out-0:
          destination: adeo-dev-europe-west1-APP-ARBOLPIM-BM-ES-P1-C1-BONSAI-DICTIONNARY-ATTRIBUTE-SYNC-V1

          producer:
            required-groups:
              - auditGroup

      kafka:
        binder:
          brokers: ${KAFKA_CLUSTER}
          auto-create-topics: false
          auto-add-partitions: false
          configuration:
            '[ssl.endpoint.identification.algorithm]': https
            '[security.protocol]': SASL_SSL
            '[sasl.jaas.config]': org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
            '[sasl.mechanism]': PLAIN
            '[request.timeout.ms]': 60000
            '[key.serializer]': io.confluent.kafka.serializers.KafkaAvroSerializer
            '[value.serializer]': io.confluent.kafka.serializers.KafkaAvroSerializer
            '[key.deserializer]': io.confluent.kafka.serializers.KafkaAvroDeserializer
            '[value.deserializer]': io.confluent.kafka.serializers.KafkaAvroDeserializer
            '[basic.auth.credentials.source]': USER_INFO
            '[schema.registry.basic.auth.user.info]': ${KAFKA_SCHEMA_USERNAME}:${KAFKA_SCHEMA_PASSWORD}
            '[specific.avro.reader]': true
          consumer-properties:
            '[key.deserializer]': io.confluent.kafka.serializers.KafkaAvroDeserializer
            '[value.deserializer]': io.confluent.kafka.serializers.KafkaAvroDeserializer
            '[schema.registry.url]': ${SCHEMA_REGISTRY_URL}
            '[basic.auth.credentials.source]': USER_INFO
            '[schema.registry.basic.auth.user.info]': ${KAFKA_SCHEMA_USERNAME}:${KAFKA_SCHEMA_PASSWORD}
            '[specific.avro.reader]': true
            '[max.poll.records]': 50
            '[fetch.max.wait.ms]': 400
            '[fetch.min.bytes]': 50000
          producer-properties:
            '[key.serializer]': io.confluent.kafka.serializers.KafkaAvroSerializer
            '[value.serializer]': io.confluent.kafka.serializers.KafkaAvroSerializer
            '[schema.registry.url]': ${SCHEMA_REGISTRY_URL}
            '[basic.auth.credentials.source]': USER_INFO
            '[schema.registry.basic.auth.user.info]': ${KAFKA_SCHEMA_USERNAME}:${KAFKA_SCHEMA_PASSWORD}

kafka:
  brokers: ${KAFKA_CLUSTER}
  ssl-endpoint-identification-algorithm: https
  sasl-jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
  schema-registry-url: ${SCHEMA_REGISTRY_URL}
  schema-registry-basic-auth-user-info: ${KAFKA_SCHEMA_USERNAME}:${KAFKA_SCHEMA_PASSWORD}
  security-protocol: SASL_SSL
  sasl-mechanism: PLAIN
  schema-auto-register: false
  basic-auth-credentials-source: USER_INFO
  topic:
    attribute-topic: ${KAFKA_TOPIC}

api:
  pagination:
    page: 0
    size: 20

security:
  access:
    users:
      -
        username: user
        password: ${USER_PASSWORD}
        authorities:
          - READER
          - WRITER

      -
        username: user_writer
        password: ${WRITER_PASSWORD}
        authorities:
          - READER
          - WRITER

      -
        username: admin
        password: ${ADMIN_PASSWORD}
        authorities:
          - READER
          - WRITER
          - ADMIN
