
logging:
  level:
    root: INFO

opensearch:
  uris: http://opensearch:9200
  username: admin
  password: admin

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: broker:9092
          auto-create-topics: true
          auto-add-partitions: true
          configuration:
            '[request.timeout.ms]': 60000
            '[key.serializer]': io.confluent.kafka.serializers.KafkaAvroSerializer
            '[value.serializer]': io.confluent.kafka.serializers.KafkaAvroSerializer
            '[key.deserializer]': io.confluent.kafka.serializers.KafkaAvroDeserializer
            '[value.deserializer]': io.confluent.kafka.serializers.KafkaAvroDeserializer
            '[specific.avro.reader]': true
          consumer-properties:
            '[key.deserializer]': io.confluent.kafka.serializers.KafkaAvroDeserializer
            '[value.deserializer]': io.confluent.kafka.serializers.KafkaAvroDeserializer
            '[schema.registry.url]': http://schema-registry:8081
            '[specific.avro.reader]': true
            '[max.poll.records]': 50
            '[fetch.max.wait.ms]': 400
            '[fetch.min.bytes]': 50000
          producer-properties:
            '[key.serializer]': io.confluent.kafka.serializers.KafkaAvroSerializer
            '[value.serializer]': io.confluent.kafka.serializers.KafkaAvroSerializer
            '[schema.registry.url]': http://schema-registry:8081
