
logging:
  level:
    root: INFO

server.port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /management
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: 10000ms
    info:
      cache:
        time-to-live: 10000ms

spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ

  application:
    name: web-lab

  threads:
    virtual:
      enabled: true

  # More information is here :
  # https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization.using-basic-sql-scripts
  sql:
    init:
      mode: always
      data-locations: classpath*:sql/data.sql
      schema-locations: classpath*:sql/schema.sql

api:
  pagination:
    page: 0
    size: 20

security:
  access:
    users:
      -
        username: user
        password: ${USER_PASSWORD}
        authorities:
          - READER
          - WRITER

      -
        username: user_writer
        password: ${WRITER_PASSWORD}
        authorities:
          - READER
          - WRITER

      -
        username: admin
        password: ${ADMIN_PASSWORD}
        authorities:
          - READER
          - WRITER
          - ADMIN
