
logging:
  level:
    root: INFO
    '[org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator]': INFO
    '[org.springframework.cloud.gateway]': TRACE

server.port: 7070

management:
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /management
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: 10000ms
    info:
      cache:
        time-to-live: 10000ms

spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ

  application:
    name: pro-gateway

  threads:
    virtual:
      enabled: false

  cloud:
    gateway:
      routes:
        - id: backend-attribute
          uri: lb://${app.backend-name}
          predicates:
            - Path=/dictionary/attributes/{segment}

        - id: backend-attributes
          uri: lb://${app.backend-name}
          predicates:
            - Path=/dictionary/attributes/**

        - id: backend-swagger-ui
          uri: lb://${app.backend-name}
          predicates:
            - Path=/openapi/**

        - id: eureka-api
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/api/{segment}
          filters:
            - SetPath=/eureka/{segment}

        - id: eureka-web
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

app:
  eureka-server: ${EUREKA_SERVER}
  backend-name: pro-backend-api

eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

microservices:
  dictionary-api-uri: ${DICTIONARY_API_URI}
  backend-api-uri: ${BACKEND_API_URI}
