
logging:
  level:
    root: INFO

server.port: 9999
server:
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /management
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: 10000ms
    info:
      cache:
        time-to-live: 10000ms

spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ

  application:
    name: auth-server

  threads:
    virtual:
      enabled: false

app:
  eureka-server: ${EUREKA_SERVER}

security:
  eureka-username: ${EUREKA_USERNAME}
  eureka-password: ${EUREKA_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://${security.eureka-username}:${security.eureka-password}@${app.eureka-server}:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

