
logging:
  level:
    root: INFO

server.port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /management
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: 10000ms
    info:
      cache:
        time-to-live: 10000ms

springdoc:
  api-docs:
    path: /openapi/v3/api-docs
  swagger-ui:
    path: /openapi/swagger-ui.html
  paths-to-match: /**
  packages-to-scan: com.springboot.learning.api.controller

opensearch:
  uris: ${OPENSEARCH_URI}
  username: ${OPENSEARCH_USERNAME}
  password: ${OPENSEARCH_PASSWORD}

spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ

  application:
    name: pro-attribute-dictionary-api

  threads:
    virtual:
      enabled: false

  cloud:
    stream:
      default-binder: kafka

      bindings:
        attributeDictionarySyncEventConsume-out-0:
          destination: adeo-dev-europe-west1-APP-ARBOLPIM-BM-ES-P1-C1-BONSAI-DICTIONARY-ATTRIBUTE-SYNC
          content-type: application/*+avro

          producer:
            use-native-encoding: true

app:
  eureka-server: ${EUREKA_SERVER}

eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

api:
  pagination:
    page: 0
    size: 20

security:
  access:
    users:
      -
        username: user
        password: ${USER_PASSWORD}
        authorities:
          - READER
          - WRITER

      -
        username: user_writer
        password: ${WRITER_PASSWORD}
        authorities:
          - READER
          - WRITER

      -
        username: admin
        password: ${ADMIN_PASSWORD}
        authorities:
          - READER
          - WRITER
          - ADMIN

service.version: v1

application:
  opensearch:
    indices:
      attributes-dictionary-name: attributes_dictionary_${INDICES_VERSION}_${spring.profiles.active}_${BU}