
logging:
  level:
    root: INFO

server:
  forward-headers-strategy: framework
  port: 9080

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /management
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: 10000ms
    info:
      cache:
        time-to-live: 5000ms

springdoc:
  api-docs:
    path: /openapi/v3/api-docs
  swagger-ui:
    path: /openapi/swagger-ui.html
    oauth2-redirect-url: /swagger-ui/oauth2-redirect.html
    oauth:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
      use-basic-authentication-with-access-code-grant: true
  oAuthFlow:
    authorizationUrl: ${OAUTH2_AUTHORIZE}
    tokenUrl: ${OAUTH2_TOKEN}
  paths-to-match: /**
  packages-to-scan: com.springboot.learning.backend.api.controller
  cache:
    disabled: true

spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ

  application:
    name: pro-backend-api

  threads:
    virtual:
      enabled: false

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${RESOURCE_SERVER_URI}
          jwk-set-uri: ${RESOURCE_SERVER_JWK_URI}
          jws-algorithms: ${RESOURCE_SERVER_JWS_ALGORITHMS}

api:
  pagination:
    page: 0
    size: 10

microservices:
  dictionary-api-uri: ${DICTIONARY_API_URI}
  dictionary-api-key: ${DICTIONARY_API_KEY}

app:
  eureka-server: ${EUREKA_SERVER}

security:
  eureka-username: ${EUREKA_USERNAME}
  eureka-password: ${EUREKA_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://${security.eureka-username}:${security.eureka-password}@${app.eureka-server}:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

resilience4j:
  timelimiter:
    instances:
      attributes:
        timeout-duration:
          seconds: 2
  circuitbreaker:
    instances:
      attributes:
        allow-health-indicator-to-fail: false
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        ignore-exceptions:
          - com.springboot.learning.backend.api.integration.exception.InvalidInputException
  retry:
    instances:
      attributes:
        max-attempts: 3
        wait-duration:
          seconds: 1
        retry-exceptions:
          - com.springboot.learning.backend.api.integration.exception.MicroserviceCalledException
